package com.welcome.auxiliary;

import java.util.Arrays;
import java.util.List;

public class SlotList {

  public static List<String> appForm = Arrays.asList("welcome:AccountStatus",
      "welcome:ActivityParticipation", "welcome:AddictionIssues", "welcome:Administrator",
      "welcome:Age", "welcome:ApartmentNumber", "welcome:ArrivalDate", "welcome:AsylumApplication",
      "welcome:AsylumClaim", "welcome:AsylumPreRegistrationNumber", "welcome:AvatarConfig",
      "welcome:Birthday", "welcome:BuildingName", "welcome:BuildingNumber", "welcome:BuildingType",
      "welcome:CertificateCatalan", "welcome:CertificateCatalanSociety",
      "welcome:CertificateLabourMarket", "welcome:CertificateSpanish", "welcome:City",
      "welcome:CityOfBirth", "welcome:CompletedModules", "welcome:CompletionYearCatalan",
      "welcome:CompletionYearCatalanSociety", "welcome:CompletionYearLabourMarket",
      "welcome:CompletionYearSpanish", "welcome:Country", "welcome:CountryCode",
      "welcome:CountryOfBirth", "welcome:CountryOfBirthCode", "welcome:CountryOfOrigin",
      "welcome:CountryOfOriginCode", "welcome:CountryOfOriginProfession",
      "welcome:CourseInstitutionCatalan", "welcome:CourseInstitutionCatalanSociety",
      "welcome:CourseInstitutionLabourMarket", "welcome:CourseInstitutionSpanish",
      "welcome:CourseNameCatalan", "welcome:CourseNameCatalanSociety",
      "welcome:CourseNameLabourMarket", "welcome:CourseNameSpanish", "welcome:CoursesCatalan",
      "welcome:CoursesLabour", "welcome:CoursesSociety", "welcome:CoursesSpanish",
      "welcome:DigitalSkills", "welcome:DoorNumber", "welcome:DurationCatalan",
      "welcome:DurationCatalanSociety", "welcome:DurationLabourMarket", "welcome:DurationOfStay",
      "welcome:DurationSpanish", "welcome:EducationLevel", "welcome:Email",
      "welcome:EmailNotifications", "welcome:EmploymentStatus", "welcome:Entrance",
      "welcome:Ethnicity", "welcome:FamilyMembers", "welcome:FirstSurname", "welcome:FloorNumber",
      "welcome:Gender", "welcome:HealthIssues", "welcome:Hobbies", "welcome:HostCountry",
      "welcome:HostCountryCode", "welcome:HostCountryProfession", "welcome:HostLangLevel",
      "welcome:IDCountry", "welcome:IDCountryCode", "welcome:IDNumber", "welcome:IDType",
      "welcome:Illiteracy", "welcome:ImmigratedAlone", "welcome:InitDataCollection",
      "welcome:KnowledgeCatalan", "welcome:KnowledgeLabour", "welcome:KnowledgeSociety",
      "welcome:KnowledgeSpanish", "welcome:Landline", "welcome:Language", "welcome:LanguageCode",
      "welcome:LccGenderPreference", "welcome:LccGenderPrefWeight", "welcome:LccNationPreference",
      "welcome:LccNationPrefWeight", "welcome:LearningHandicap", "welcome:LegalStatus",
      "welcome:MaritalStatus", "welcome:MobilePhone", "welcome:Municipality", "welcome:Name",
      "welcome:Nationality", "welcome:NationalityCode",
      "welcome:NativeLanguageName",
      "welcome:NativeLanguageCode",
      "welcome:NotificationPreferences",
      "welcome:NumberAccompaniedChildren",
//      "welcome:OtherLanguage", "welcome:OtherLanguageCode",
      "welcome:PendingModules", "welcome:PostalAddress", "welcome:PostCode",
      "welcome:PreferredLanguage", "welcome:PreferredLanguageCode",
      "welcome:PreviousResidenceCatalonia", "welcome:PreviousResidenceOther",
      "welcome:PreviousResidenceOtherCode", "welcome:PreviousResidenceSpain",
      "welcome:PrevResidenceBuildingNumber", "welcome:PrevResidenceCity",
      "welcome:PrevResidenceCountry", "welcome:PrevResidencePostCode",
      "welcome:PrevResidenceProvince", "welcome:PrevResidenceStreetName", "welcome:Province",
      "welcome:RegistrationDate", "welcome:RegistrationStatus", "welcome:RegistrationYear",
      "welcome:ResidenceStatus", "welcome:Route", "welcome:RouteStartDate", "welcome:SecondSurname",
      "welcome:SMSNotifications", "welcome:StreetName", "welcome:StreetNumber",
      "welcome:StreetType", "welcome:TotalNumberChildren", "welcome:UserId", "welcome:Username",
      "welcome:WorkExperienceCountryOfOrigin", "welcome:WorkPermit", "welcome:YearArrivalCity",
      "welcome:YearArrivalCountry", "welcome:YearArrivalRegion", "welcome:Classroom");
}
/*
 * "welcome:MotherTongue","welcome:FamilyStatus", "welcome:PreferredLanguage",
 * "welcome:PreferredLanguageCode", "welcome:StreetNumber", "welcome:PostalAddress",
 * "welcome:RegistrationDate","welcome:AccountStatus", "welcome:DegreeTitle",
 * "welcome:DegreeCertificate", "welcome:InstitutionName", "welcome:GraduationYear",
 * "welcome:GraduationStatus", "welcome:CompletedCourses", "welcome:DegreeGrade",
 * "welcome:DegreeTitle", "welcome:DegreeCertificate", "welcome:InstitutionName",
 * "welcome:GraduationYear", "welcome:GraduationStatus", "welcome:CompletedCourses",
 * "welcome:DegreeGrade", "welcome:AdditionalEducation", "welcome:IntroductionEducation",
 * "welcome:InitDataCollection", "welcome:AvatarConfig", "welcome:AsylumPreRegistrationNumber"
 */
